export type DocSection = { id: string; title: string; paragraphs: string[]; code?: string; note?: string; links?: { label: string; href: string }[] };
export type Doc = { slug: string; title: string; group: string; description: string; minutes: number; sections: DocSection[] };
export const docs: Doc[] = [
  { slug: "installation", title: "Installation", group: "Start here", description: "Install a complete local workspace with one command.", minutes: 3, sections: [
    { id: "requirements", title: "What you need", paragraphs: ["Loom includes its JavaScript runtime and browser UI. You do not need Node.js, npm, or Bun to run a release build. Install Git and OpenCode first, and configure a model provider in OpenCode.", "Release targets are macOS on Apple silicon and Intel, Linux on x64 and arm64 with glibc, and Windows x64. Alpine/musl and Windows ARM64 are not included in the initial release matrix. The release CI runs a native startup check on each target."], links: [{ label: "Install Git", href: "https://git-scm.com/downloads" }, { label: "Set up OpenCode", href: "https://opencode.ai/docs/" }] },
    { id: "install", title: "Install Loom", paragraphs: ["Run the command above in Terminal on macOS/Linux, or PowerShell on Windows. The installer finds the latest stable GitHub release, downloads your platform binary, verifies SHA-256, and adds Loom to your user PATH. It does not require administrator access.", "The installer needs a published release. If it reports that no release is available, check GitHub Releases. The source repository can be built locally by contributors; the installer does not build from source."], links: [{ label: "Browse releases and checksums", href: "https://github.com/MrPinguiiin/loom/releases" }, { label: "Review the shell installer", href: "https://github.com/MrPinguiiin/loom/blob/main/install.sh" }, { label: "Review the PowerShell installer", href: "https://github.com/MrPinguiiin/loom/blob/main/install.ps1" }] },
    { id: "open", title: "Open your workspace", paragraphs: ["Restart your terminal so it picks up the PATH change, then run Loom. It opens the local UI on 127.0.0.1:4317. The daemon continues running after the terminal command returns."], code: "loom\nloom doctor", note: "If your browser does not open automatically, enter http://127.0.0.1:4317 in its address bar." },
    { id: "location", title: "Where it lives", paragraphs: ["Loom installs to ~/.loom/bin/loom on macOS/Linux and $HOME\\.loom\\bin\\loom.exe on Windows. Its configuration, SQLite database, logs, cache, and managed worktrees stay under the same .loom directory.", "For a custom location, set LOOM_HOME to an absolute path before installing and keep that environment variable set whenever you run Loom. Updating an existing installation uses loom update, rather than rerunning the installer."] },
  ] },
  { slug: "getting-started", title: "Getting started", group: "Start here", description: "Go from a local repository to your first reviewed change.", minutes: 5, sections: [
    { id: "project", title: "1. Add a project", paragraphs: ["Start Loom, then add the absolute path to a local Git repository from the workspace sidebar. The repository needs at least one commit. Configure your Git author name and email so task branches can be committed.", "Choose a small, verifiable change for your first run. A documentation correction or a focused bug fix makes it easier to follow the complete workflow."] },
    { id: "conversation", title: "2. Start with a conversation", paragraphs: ["Select your project and send a message. OpenCode replies in the chat pane. Type @ to reference a project file, and select your configured model or agent in the composer.", "Sessions keep their own conversation history. The session identifier in the URL lets you return to the same conversation. File edits and tool output appear alongside the response."] },
    { id: "epic", title: "3. Turn a goal into a plan", paragraphs: ["Create an Epic for work that benefits from several tasks. Describe the goal and the expected result. Review the proposed task titles, prompts, dependencies, and project commands.", "Edit the plan before starting. Only approve install, lint, test, and build commands you understand. They run in the integration workspace and can access the machine with your user permissions."] },
    { id: "review", title: "4. Review the result", paragraphs: ["Follow task states in the Kanban board and inspect their conversations. When tasks finish, open the integration review. Read the combined diff and check results, including any failed checks and repair attempts.", "Make the main project checkout clean before approving the merge. Approval applies to the exact reviewed commit. If the integration changes, review its new head again."] },
  ] },
  { slug: "opencode", title: "OpenCode requirements", group: "Start here", description: "Connect the agent runtime and your preferred model provider.", minutes: 3, sections: [
    { id: "runtime", title: "Install and configure OpenCode", paragraphs: ["Loom orchestrates work through OpenCode. Install the OpenCode executable from its official documentation, launch it once, and connect your model provider. Verify that a simple prompt works before starting a Loom task.", "Loom discovers opencode (opencode.exe on Windows) on PATH. If you use a custom executable location, set OPENCODE_BIN to its absolute path. Native Windows executable installs are recommended over .cmd wrappers."], links: [{ label: "OpenCode documentation", href: "https://opencode.ai/docs/" }] },
    { id: "server", title: "How Loom connects", paragraphs: ["Loom checks the OpenCode server at 127.0.0.1:4096. It reuses a healthy server or starts opencode serve bound to loopback. A server started by Loom is stopped with Loom; an existing external server remains yours to manage.", "Keep this port local. If another application is using it, resolve that conflict before starting Loom. Run loom doctor to check executable discovery."], code: "opencode --version\nloom doctor" },
    { id: "providers", title: "Models, costs, and permissions", paragraphs: ["Provider credentials and model access are managed through OpenCode. Loom does not include model credits. Usage follows the terms and pricing of the provider you configure.", "Agents may request permission before running commands. Inspect the command, directory, and reason before allowing it. Do not assume a separate Git worktree is an operating-system sandbox."] },
  ] },
  { slug: "project-safety", title: "Project safety", group: "Working with agents", description: "Understand the boundaries before you give an agent a task.", minutes: 3, sections: [
    { id: "boundaries", title: "A worktree isolates changes", paragraphs: ["Each task has a separate checkout and branch. That keeps concurrent edits out of your main working directory. It does not restrict the filesystem, network, or process permissions of commands run by an agent.", "Use repositories you trust. Review project scripts and instructions before starting work, especially in downloaded repositories."] },
    { id: "permissions", title: "Review commands and permissions", paragraphs: ["Review the Epic's validation commands before approval. Install commands can run dependency lifecycle scripts. Read runtime permission requests and grant only what the task needs.", "Avoid putting secrets in task prompts or artifact summaries. If a secret is accidentally sent to a provider, rotate it through that provider's credential management."] },
    { id: "merge", title: "Keep merges deliberate", paragraphs: ["Before merging, inspect the diff and tests and keep the target checkout clean. Integration review checks the approved commit and base so stale approval cannot silently merge a changed result.", "Discard a worktree through Loom after reviewing its contents. Back up work you want to keep before deletion. Uninstalling Loom intentionally keeps your branches and worktrees."] },
  ] },
  { slug: "parallel-tasks", title: "Parallel tasks & Epics", group: "Working with agents", description: "Plan dependencies, follow progress, and bring branches together.", minutes: 4, sections: [
    { id: "plan", title: "Review the task graph", paragraphs: ["An Epic contains a goal and a task plan. Each task has a stable key, a prompt, and dependency keys. Independent tasks can run together within the scheduler's concurrency limits; dependent tasks wait.", "A plan cannot contain duplicate keys, missing dependencies, or a cycle. Keep tasks focused and describe the contract a dependent task should receive."] },
    { id: "board", title: "Manage the board", paragraphs: ["Use the Kanban board to follow queued, running, completed, failed, and review states. Open a task to inspect its output, session, worktree, and diff.", "If a dependency fails, its descendants remain blocked. Fix the cause and explicitly retry. A retry has its own run history; cancellation waits for the active process to release its capacity."] },
    { id: "artifacts", title: "Share useful artifacts", paragraphs: ["Tasks can write .loom/artifacts.json to describe outputs for subsequent work. Entries contain a type, relative path, and concise summary. Loom validates and stores the metadata; the manifest itself is excluded from task commits to avoid unnecessary conflicts.", "Artifacts are context, not a mechanism for executing code. Keep paths inside the workspace and omit secrets."], code: '{\n  "artifacts": [\n    { "type": "documentation", "path": "docs/api.md", "summary": "Defines the request and response contract." }\n  ]\n}' },
    { id: "integration", title: "Integrate and approve", paragraphs: ["Loom merges task branches into a dedicated integration workspace, then runs the approved checks. An integration agent can attempt repairs; a conflict resolver can propose resolutions. The review retains check outputs and the resulting diff.", "A successful automated check does not approve a merge. You review the combined changes and authorize the exact head to merge into the project branch."] },
  ] },
  { slug: "worktrees", title: "Git worktrees", group: "Working with agents", description: "Know where task files live and how to recover them.", minutes: 3, sections: [
    { id: "location", title: "Find task files", paragraphs: ["Managed worktrees live under ~/.loom/worktrees, organized by project and task/run. Open the task details to find the exact path and branch.", "These are real Git worktrees. You can inspect a retained workspace using your editor and standard Git commands."], code: "git worktree list\ngit -C /path/to/worktree status" },
    { id: "recovery", title: "After an interrupted run", paragraphs: ["On restart, Loom reconciles interrupted work and preserves workspaces for inspection. Check the task's error and history before retrying. Do not delete metadata files to force a running task back into a different state.", "Run loom doctor if a registered workspace is missing. Restore it from your backup or resolve the affected task in the UI."] },
    { id: "cleanup", title: "Clean up deliberately", paragraphs: ["Use the task's discard action after reviewing its changes. Only remove branches manually when you understand which commits they contain. Git worktree prune removes stale administrative entries; it does not recover uncommitted files.", "Removing a project from the sidebar or uninstalling Loom should not be used as a substitute for reviewing and cleaning up task work."] },
  ] },
  { slug: "updates", title: "Updates & rollback", group: "Maintain your install", description: "Move between verified releases without replacing a running binary.", minutes: 4, sections: [
    { id: "check", title: "Check for a release", paragraphs: ["Loom checks its configured channel at startup and at most once every six hours. The request has a short timeout; network failures do not prevent startup. You can also check from the update control in the UI.", "Stable is the default. A beta can contain changes that have not reached stable. A newer stable release replaces an older beta; Loom does not silently downgrade your installation."], code: "loom update\nloom update --channel beta" },
    { id: "install", title: "Update and restart", paragraphs: ["Finish active tasks, Epic planning/integration, and OpenCode chats first. Select Update & Restart in the UI or run loom update. The update checks the official manifest, downloads your platform artifact, and verifies both SHA-256 and size.", "A helper copied from the current trusted binary stops the daemon, preserves the previous executable and local database, replaces the executable, and checks the new daemon's health. No script from the release manifest is executed."] },
    { id: "rollback", title: "If startup fails", paragraphs: ["The helper restores the previous binary and database snapshot if the new daemon fails its startup check. Read loom logs for the result. The update control also displays the last update result.", "A power loss can interrupt any filesystem operation. If Loom cannot start, inspect ~/.loom/bin/loom.previous (loom.exe.previous on Windows) and ~/.loom/cache/update.lock before removing anything. Retain that directory's database backup and ask for help through a GitHub issue with redacted logs."], code: "loom logs\nloom doctor", links: [{ label: "Report an update problem", href: "https://github.com/MrPinguiiin/loom/issues" }] },
    { id: "settings", title: "Control update checks", paragraphs: ["The UI update settings let you choose stable/beta and disable automatic checks. These values are stored as releaseChannel and updateChecks in config.json. The explicit Check now and loom update commands still contact GitHub when requested.", "The application version and protocolVersion are separate. A packaged UI ships with its compatible daemon. Do not mix frontend assets from another release."] },
  ] },
  { slug: "uninstall", title: "Uninstall", group: "Maintain your install", description: "Remove Loom while keeping your project work safe.", minutes: 2, sections: [
    { id: "binary", title: "Remove the executable", paragraphs: ["First run loom uninstall to see what will be removed. Add --yes to confirm removal of the installed binary. Loom stops its daemon and keeps app state, logs, branches, and worktrees by default."], code: "loom uninstall\nloom uninstall --yes" },
    { id: "logs", title: "Choose whether to keep logs", paragraphs: ["Add --logs if you also want local daemon logs removed. This does not remove task branches or the state database."], code: "loom uninstall --yes --logs" },
    { id: "data", title: "Review retained data", paragraphs: ["The remaining ~/.loom directory includes config.json, state.db, cache, and worktrees. Review task changes and discard managed worktrees through Loom before manually deleting state. Deleting a worktree directory can permanently lose uncommitted edits.", "After removal, you may delete the Loom PATH line from your shell profile or the Loom bin directory from Windows User Path. The installer marks its shell line with a # Loom comment."] },
  ] },
  { slug: "troubleshooting", title: "Troubleshooting", group: "Maintain your install", description: "Find the failing layer before changing your workspace.", minutes: 4, sections: [
    { id: "doctor", title: "Start with the doctor", paragraphs: ["Run the doctor from your terminal. It reports platform support, Git/OpenCode discovery, directory permissions, SQLite health, daemon port availability, workspace paths, and update state. A free daemon port before the first start is expected."], code: "loom doctor\nloom logs" },
    { id: "path", title: "“loom: command not found”", paragraphs: ["Restart the terminal after installation. On macOS/Linux, try ~/.loom/bin/loom --version directly. On Windows, try & \"$HOME\\.loom\\bin\\loom.exe\" --version. If this succeeds, check the PATH entry in your shell profile or User environment variables.", "If the installer cannot find a release, check GitHub Releases. Corporate proxies, offline networks, or a channel that has not yet been published can prevent installation."] },
    { id: "startup", title: "The UI will not open", paragraphs: ["Open http://127.0.0.1:4317 manually. Check loom logs for an unavailable OpenCode executable, an occupied port, or an unreadable data directory. Restart with loom restart after fixing the reported problem.", "Do not expose the daemon through a public tunnel. Host and Origin checks intentionally reject requests from other sites. In development, configure CORS_ORIGIN to the Vite origin; release builds serve the UI from the daemon's own origin."] },
    { id: "chat", title: "A chat or task is stuck", paragraphs: ["Verify that OpenCode can answer the same simple prompt directly. Check your provider credentials, model availability, and any pending permission request in Loom.", "Inspect the task's last error and output before retrying. After a daemon interruption, a retained worktree is expected. Do not delete it until you have reviewed or saved its contents."] },
    { id: "support", title: "Share a useful bug report", paragraphs: ["Include your OS/architecture, loom --version output, the command or UI action, and relevant log lines. Remove tokens, credentials, private paths, prompt content, and source code before publishing logs."], links: [{ label: "Open a GitHub issue", href: "https://github.com/MrPinguiiin/loom/issues" }] },
  ] },
  { slug: "privacy", title: "Privacy", group: "Trust & boundaries", description: "Understand what stays local and what goes over the network.", minutes: 3, sections: [
    { id: "local", title: "Local workspace data", paragraphs: ["Loom stores project references, task and Epic state, artifact metadata, configuration, and logs on your machine under ~/.loom. Git repositories and worktrees remain local. This release does not include a Loom cloud account, repository upload, telemetry, or cloud sync."] },
    { id: "providers", title: "Agent requests", paragraphs: ["OpenCode communicates with the model provider you configure. Prompts, selected files, tool output, and other task context may be sent to that provider. Its retention and data policies apply.", "Local orchestration does not mean local model inference. Choose a local model provider if your workflow requires it, and verify your OpenCode configuration."] },
    { id: "updates", title: "Release requests", paragraphs: ["Automatic update checks contact GitHub for a release manifest. Installation and updates download binaries from GitHub. These services can see ordinary request metadata such as your IP address. Disable automatic checks in update settings if desired.", "This documentation site uses local fonts and no analytics or tracking scripts. GitHub links and installation commands connect to GitHub only when followed or executed."] },
    { id: "retention", title: "Data you choose to remove", paragraphs: ["Uninstall keeps state and worktrees so you do not lose unfinished work. Review retained data before deleting it manually. Treat database files, artifact summaries, logs, and agent sessions as potentially sensitive."] },
  ] },
  { slug: "security", title: "Security", group: "Trust & boundaries", description: "The local trust model and the limits it is designed around.", minutes: 4, sections: [
    { id: "daemon", title: "Local daemon access", paragraphs: ["The daemon binds to 127.0.0.1. API calls require a bearer token stored in a private config file. Browser bootstrap is limited to the configured local Origin. Host validation reduces DNS rebinding exposure, and WebSocket access requires the daemon token.", "The UI device lock is a convenience privacy screen, not an independent authentication boundary. A process with access to your user account and config file can access Loom. Protect your operating-system account and do not share your daemon token."] },
    { id: "agents", title: "Agent execution is trusted code", paragraphs: ["Git worktrees isolate repository changes, not process capabilities. Agents and approved project commands execute with your user privileges. Malicious repository instructions, package scripts, or model output can still attempt unsafe operations.", "Review plans and permission requests. Use OS containers or another restricted environment when the repository or its scripts are not trusted."] },
    { id: "updater", title: "Release integrity", paragraphs: ["The updater accepts HTTPS artifacts only from the official repository's versioned GitHub releases. It validates manifest shape, file size, and SHA-256 before using an executable. Updates are applied by a copy of the current executable, and a failed health check triggers rollback.", "Checksums protect against corrupt or substituted downloads relative to the trusted manifest. They do not protect against a compromised maintainer or GitHub release account. Release workflow permissions and repository protection are part of the trust boundary."] },
    { id: "report", title: "Report a vulnerability", paragraphs: ["Use the repository's private vulnerability reporting option when available. Do not put live credentials or exploitable private-system details in a public issue. See SECURITY.md in the repository for the reporting policy."], links: [{ label: "Repository security policy", href: "https://github.com/MrPinguiiin/loom/blob/main/SECURITY.md" }] },
  ] },
];
