<script lang="ts">
  import { ArrowLeft, ArrowRight, ArrowUpRight, Info } from "@lucide/svelte";
  import InstallCommand from "$lib/InstallCommand.svelte";
  import { sitePath, repository } from "$lib/config";
  import type { PageData } from "./$types";
  let { data }: { data: PageData } = $props();
</script>
<svelte:head><title>{data.doc.title} — Loom docs</title><meta name="description" content={data.doc.description}/></svelte:head>
<div class="article-layout"><main id="main" class="doc-article"><div class="breadcrumbs"><a href={sitePath("/docs/")}>Docs</a><span>/</span><span>{data.doc.group}</span></div><header><p class="eyebrow">{data.doc.minutes} MINUTE READ</p><h1>{data.doc.title}</h1><p class="docs-lead">{data.doc.description}</p></header>{#if data.doc.slug === "installation"}<div class="docs-install glass"><InstallCommand/></div>{/if}{#each data.doc.sections as section}<section id={section.id}><h2><a href={`#${section.id}`}>{section.title}</a></h2>{#each section.paragraphs as paragraph}<p>{paragraph}</p>{/each}{#if section.code}<pre><code>{section.code}</code></pre>{/if}{#if section.note}<aside class="doc-callout"><Info size={17}/><p>{section.note}</p></aside>{/if}{#if section.links}<div class="doc-links">{#each section.links as link}<a href={link.href}>{link.label}<ArrowUpRight size={13}/></a>{/each}</div>{/if}</section>{/each}<div class="doc-edit"><a href={`${repository}/blob/main/apps/site/src/lib/docs.ts`}>Improve this page <ArrowUpRight size={13}/></a></div><nav class="doc-pagination" aria-label="Next documentation pages">{#if data.previous}<a href={sitePath(`/docs/${data.previous.slug}/`)}><span><ArrowLeft size={13}/> Previous</span>{data.previous.title}</a>{/if}{#if data.next}<a href={sitePath(`/docs/${data.next.slug}/`)}><span>Next <ArrowRight size={13}/></span>{data.next.title}</a>{/if}</nav></main><aside class="doc-toc"><p>ON THIS PAGE</p>{#each data.doc.sections as section}<a href={`#${section.id}`}>{section.title}</a>{/each}<div><span class="live-dot"></span> Made for local work.</div></aside></div>
