name: Version release
on:
  push:
    branches: [main]
permissions:
  contents: write
  pull-requests: write
jobs:
  version:
    runs-on: ubuntu-24.04
    outputs:
      released: ${{ steps.release.outputs.release_created }}
      tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
  binaries:
    if: needs.version.outputs.released == 'true'
    needs: version
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.version.outputs.tag }}
